### ISSUE TITLE
Signature and Public Key not populated for intoto types

### ISSUE THREAD

**Issue by spencerschrock** [sigstore/rekor-search-ui#69]
**Description**

When viewing [the entry with log index 44413894](https://search.sigstore.dev/?logIndex=44413894) the `Signature` and `Public Key` entries aren't being shown, despite the raw body having a `publicKey`.
 

<img width="881" alt="Screenshot 2024-02-28 at 1 12 38 PM" src="https://github.com/sigstore/rekor-search-ui/assets/6064089/6f47d662-057e-428d-bd75-60f7d961d0cd">

The public key is being populated for hashedrekord types:
https://search.sigstore.dev/?logIndex=74386860

**Version**

The intoto schema is v0.0.1 and was generated with
`slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0`
https://github.com/ossf/scorecard/blob/4ae4ba246c258be61ff92918eceef02fabcd5359/.github/workflows/goreleaser.yaml#L72-L81

Specifically this corresponds to provenance generated for the [v4.13.1 release of Scorecard](https://github.com/ossf/scorecard/releases/tag/v4.13.1).

**Comment by haydentherapper** [comment]
Looking at https://github.com/sigstore/rekor-search-ui/blob/7f3e7146c868d546637f0cbd14c718d482970a20/src/modules/components/Entry.tsx#L130-L132, my guess is because this is an intoto v0.0.1 type, rather than v0.0.2, so parsing fails, I guess silently. You can see the same thing with https://search.sigstore.dev/?logIndex=74413899, also v001. v002 correctly is parsed - https://search.sigstore.dev/?logIndex=10406797. I think we just need to add parsing for the v001 type.

Do you know where the provenance was generated? v001 is the older format, we shouldn't be using it anymore.
